name: NexusBlock
version: '${project.version}'
main: xhyrom.nexusblock.NexusBlock
api-version: 1.13
authors: [ xHyroM ]
softdepend:
  - HolographicDisplays
  - DecentHolograms
  - Holograms
  - CMI
  - CMILib
  - Multiverse-Core
  - MultiWorld

commands:
  nexusblock:
    description: Setup blocks or check informations
    aliases:
      - blocknexus
